### PR TITLE
Consider correctly absolute url with //

### LINKED ISSUE #46: getAnchorUrls does not work on href="//foo.com" links
Sometimes, an a tag contains an href like `"//www.foo.com/bar"` meaning that the protocol of the link is the same as the current window but it is indeed not a relative url but an absolute one.

On the youtube home page

``` html
<a href="//www.youtube.com/upload">...</a>
```

pjscrape function will get the url as http://www.foo.com//www.foo.com/bar leading to a 404 error when the page is visited.

### PR DESCRIPTION
**Pull request by Uelb**
This commit fixes #46

### CODE REVIEW

File: client/pjscrape_client.js [hunk 1]
```diff
@@ -36,6 +36,8 @@ window._pjs = (function($) {
     function toFullUrl(url) {
         // non-existent, or fully qualified already
         if (!url || url.indexOf(base) === 0 || !isLocalUrl(url)) return url;
+        // absolute url beginning with // (same protocol as the current location)
+        if(url[0] == '/' && url[1] == '/') return loc.protocol + url;
```
Comment (nrabinowitz) [inline client/pjscrape_client.js]: This is a good addition, but an odd implementation - maybe just 

```
if (url.indexOf('//') === 0) return loc.protocol + url;
```

**Comment by Uelb** [comment]
I updated the implementation :)

**Comment by nrabinowitz** [comment]
Thanks! Merging.
